Demo/idfdemo/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path




urlpatterns = [
    path('admin/', admin.site.urls),

    # Django auth app urls
    path('auth/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),

    # My apps urls (routes)
    path('', include('parea.urls', namespace='parea')),
    path('', include('marea.urls', namespace='marea')),
    path('products/', include('products.urls', namespace='products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Demo/marea/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView




app_name = 'marea'


urlpatterns = [
    path('', login_required(TemplateView.as_view(template_name='marea/home.html')), name='home'),
]

Demo/parea/urls.py
from django.urls import path

from .views import RegisterView




app_name = 'parea'


urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
]

Demo/products/urls.py
from django.urls import path
from .views import ProductCreateView
from .views import ProductDeleteView
from .views import ProductDetailView
from .views import ProductListView
from .views import ProductUpdateView




app_name = 'products'


urlpatterns = [
    path('create/', ProductCreateView.as_view(), name='create'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('', ProductListView.as_view(), name='list'),
]

Demo/marea/models.py
from django.db import models

# Create your models here.

Demo/parea/models.py
from django.db import models

# Create your models here.

Demo/products/models.py
# Required for generating thumbnail
import os.path
from django.core.files.base import ContentFile
from io import BytesIO
from PIL import Image

from django.db import models





THUMB_SIZE = (256, 256)


class Product(models.Model):
    title = models.CharField(max_length=80, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    edited_at = models.DateTimeField(auto_now=True, blank=True)
    image = models.ImageField(upload_to='user/images', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='user/images/thumbnails', editable=False)


    def save(self, *args, **kwargs):
        if not self.make_thumbnail():
            # TODO: Set to a default thumbnail
            # raise Exception('Could not create thumbnail. File type not supported.')
            pass

        super().save(*args, **kwargs)


    def make_thumbnail(self):
        if self.image:
            image = Image.open(self.image)
            image.thumbnail(THUMB_SIZE, Image.ANTIALIAS)

            thumb_name, thumb_extension = os.path.splitext(self.image.name)
            thumb_extension = thumb_extension.lower()

            thumb_filename = thumb_name + '_thumb' + thumb_extension

            if thumb_extension in ['.jpg', '.jpeg']:
                FTYPE = 'JPEG'
            elif thumb_extension == '.gif':
                FTYPE = 'GIF'
            elif thumb_extension == '.png':
                FTYPE = 'PNG'
            else:
                # Unrecognized file type
                return False

            # Save thumbnail to in-memory file as StringIO
            temp_thumb = BytesIO()
            image.save(temp_thumb, FTYPE)
            temp_thumb.seek(0)

            # set save=False, otherwise it will run in an infinite loop
            self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
            temp_thumb.close()

            return True
        
        return False

Demo/parea/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm




UserModel = get_user_model()


class RegisterForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('first_name', 'email', 'username')

Demo/marea/views.py
from django.shortcuts import render

# Create your views here.

Demo/parea/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import RegisterForm



UserModel = get_user_model()


class RegisterView(CreateView):
    model = UserModel
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('auth:login')
    success_message = 'Account was successfuly registered.'


    def form_valid(self, form):
        messages.success(self.request, self.success_message)

        return super().form_valid(form)

Demo/products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .models import Product




class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['title', 'description', 'price', 'image']
    success_url = reverse_lazy('products:list')




class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('products:list')




class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product




class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    paginate_by = 10




class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['title', 'description', 'price', 'image']
    success_url = 'products:detail'


    def get_success_url(self):
        if not self.success_url:
            raise ImproperlyConfigured('No URL to redirect to. Provide a success_url.')
        return reverse(self.success_url, kwargs={'pk': self.object.id})

Demo/marea/templates/marea/home.html
{% extends 'marea/layout.html' %}


{% block content %}
    <h1>Welcome to Indeform Django Demo Home Page</h1>

    <p class="lead">This example was created using Bootstrap 4 framework.<br> It implements simple product model with main CRUD functions.</p>
{% endblock content %}

Demo/marea/templates/marea/layout.html
{% load static %}
{% include 'shared/header.html' %}
{% include 'marea/navigation.html' %}


<main role="main" class="container">
    <div class="starter-template">
        {% block content %}
        {% endblock content %}
    </div>
</main>


{% include 'shared/footer.html' %}

Demo/marea/templates/marea/navigation.html
{% load static %}


{% url 'marea:home' as home_page %}                    
{% url 'products:create' as product_create_page %}
{% url 'products:list' as product_list_page %}


<nav class="navbar navbar-expand-lg navbar-dark bg-indeform shadow-lg">
    <a class="navbar-brand" href="#">
        <img class="d-inline-block align-top logo-nav" src="{% static 'css/img/logo-white.svg' %}">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == home_page %}active{% endif %}">
                <a class="nav-link" href="{% url 'marea:home' %}">Home</a>
            </li>
            <li class="nav-item dropdown {% if request.path == product_create_page or request.path == product_list_page %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Products
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item {% if request.path == product_create_page %}active{% endif %}" href="{% url 'products:create' %}">Create product</a>
                    <a class="dropdown-item {% if request.path == product_list_page %}active{% endif %}" href="{% url 'products:list' %}">Products list</a>
                </div>
            </li>
        </ul>

        <span class="mr-3">{{ user.first_name }} {{ user.last_name }}</span>
        <a class="btn btn-outline-indeform" href="{% url 'auth:logout' %}">Logout</a>
    </div>
</nav>

Demo/marea/templates/marea/pagination.html
{% if is_paginated %}
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}

            {% for page in paginator.page_range %}
                <li class="page-item {% if page == page_obj.number %}active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

Demo/parea/templates/parea/layout.html
{% load static %}
{% include 'shared/header.html' %}


<main role="main" class="container login">
    <div class="starter-template">
        {% block content %}
        {% endblock content %}
    </div>
</main>


{% include 'shared/footer.html' %}

Demo/products/templates/products/product_confirm_delete.html
{% extends 'marea/layout.html' %}


{% block content %}
    <h1 class="mb-5">Delete product</h1>

    <form action="{% url 'products:delete' product.id %}" method="post">
        {% csrf_token %}

            <h5 class="mb-5">Are you sure you want to delete <span class="font-italic font-weight-bold">{{ product.title }}</span>?</h3>
        
            <div>
                <a class="btn btn-indeform" href="{% url 'products:detail' product.id %}" role="button">Cancel</a>
                <button class="btn btn-indeform-danger" type="submit">Delete</button>
            </div>
        </form>
{% endblock content %}

Demo/products/templates/products/product_detail.html
{% extends 'marea/layout.html' %}
{% load static %}
{% load humanize %}


{% block content %}
    <h1 class="mb-5">Products details</h1>

    <div class="col-md-6">
        <div class="card mb-8 shadow-lg">
            <img class="card-img-top" src="{% if product.thumbnail %}{{ product.thumbnail.url }}{% elif product.image %}{{ product.image.url }}{% else %}{% static 'css/img/placeholder.png' %}{% endif %}">
            <div class="card-body">
                <h5 class="card-title">{{ product.title }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text">{{ product.price }}&euro;</p>

                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-sm btn-indeform-danger" href="{% url 'products:delete' product.id %}" role="button">Delete</a>
                        <a class="btn btn-sm btn-indeform" href="{% url 'products:update' product.id %}" role="button">Update</a>
                    </div>
                    <small>Last time edited: {{ product.edited_at|naturaltime }}</small>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Demo/products/templates/products/product_form.html
{% extends 'marea/layout.html' %}


{% block content %}
    {% if form.instance.id %}
        <h1>Update product</h1>
    {% else %}
        <h1 class="mb-5">Create new product</h1>
    {% endif %}

    <form class="form" action="
            {% if form.instance.id %}
                {% url 'products:update' form.instance.id %}
            {% else %}
                {% url 'products:create' %}
            {% endif %}"
            method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <input class="form-control shadow-lg" type="{{ form.title.field.widget.input_type }}" name="{{ form.title.name }}" placeholder="Title" value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
        
            {% if form.title.errors %}
                <div class="msg error">
                    {% for error in form.title.errors %}
                        {{ error|escape }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <input class="form-control shadow-lg" type="{{ form.price.field.widget.input_type }}" name="{{ form.price.name }}" placeholder="123.45" step=".01" value="{% if form.price.value %}{{ form.price.value }}{% endif %}">
        
            {% if form.price.errors %}
                <div class="msg error">
                    {% for error in form.price.errors %}
                        {{ error|escape }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <textarea class="form-control shadow-lg" name="{{ form.description.name }}" placeholder="Description" rows="3">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
        
            {% if form.description.errors %}
                <div class="msg error">
                    {% for error in form.description.errors %}
                        {{ error|escape }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <div class="custom-file">
                <input id="{{ form.image.id_for_label }}" class="custom-file-input" name="{{ form.image.name }}" type="{{ form.image.field.widget.input_type }}">
                <label for="{{ form.image.id_for_label }}" class="custom-file-label">Upload image</label>
            </div>

            {% if form.image.errors %}
                <div class="msg error">
                    {% for error in form.image.errors %}
                        {{ error|escape }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <button class="btn btn-indeform btn-block shadow-lg mt-5" type="submit">
            {% if form.instance.id %}
                Update
            {% else %}
                Create
            {% endif %}
        </button>
    </form>
{% endblock content %}

Demo/products/templates/products/product_list.html
{% extends 'marea/layout.html' %}
{% load static %}


{% block content %}
    <h1 class="mb-5">Products list</h1>
    
    <table class="table table-hover shadow-lg">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            {% if product_list %}
                {% for product in product_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>
                            <a href="{% url 'products:detail' product.id %}">
                                {{ product.title }}
                            </a>
                        </td>
                        <td>{{ product.description }}</td>
                        <td>{{ product.price }}&euro;</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">There is no products.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>

    {% include 'marea/pagination.html' %}
{% endblock content %}

Demo/templates/shared/footer.html
<footer class="footer">
    <div class="container">
        <span class="text-muted">&copy; {% now 'Y' %} Indeform Ltd. <a href="http://www.indeform.com">www.indeform.com</a></span>
    </div>
</footer>
</body>
</html>

Demo/templates/shared/header.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <title>Indeform Django Demo</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google font Roboto -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i&amp;subset=latin-ext" rel="stylesheet">

    <!-- Bootstrap v4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Custom css -->
    <link href="{% static 'css/general.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/parea.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/marea.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/products.css' %}" rel="stylesheet" type="text/css">
</head>
<body>